### ISSUE TITLE
Floating UI works as expected in dev mode but not in production mode

### ISSUE THREAD

**Issue by baseplate-admin** [skeletonlabs/floating-ui-svelte#128]
### Current Behavior

Here is how floating-ui looks in production mode:

[screen-recorder-tue-may-28-2024-10-05-21.webm](https://github.com/skeletonlabs/floating-ui-svelte/assets/61817579/bf3daad4-92b5-457b-9df7-c508c51f5f6b)

### Expected Behavior

Here is how it looks in development mode:

[screen-recorder-tue-may-28-2024-10-05-04.webm](https://github.com/skeletonlabs/floating-ui-svelte/assets/61817579/8552678e-6947-49b8-bdc5-b62799378cbb)

### Steps To Reproduce

This is for dev build:

1. `git clone https://github.com/baseplate-admin/coreproject-v4-ui.git`
2. `cd coreproject-v4-ui`
3. `npm run dev`

This is for production build:
1. `git clone https://github.com/baseplate-admin/coreproject-v4-ui.git`
2. `cd coreproject-v4-ui`
3. `npm run build:node`
4. `npm run preview`

### Link to Reproduction / Stackblitz

https://coreproject-v4-ui.vercel.app/anime

### More Information

Relevant codes :
https://github.com/baseplate-admin/coreproject-v4-ui/blob/e290baa4cf5c7fc19245450bd9d0860364f2a300/src/routes/anime/%2Bpage.svelte#L447-L493

**Comment by baseplate-admin** [comment]
Overriding the component like this :

```svelte
{#if sidebar_tooltips_open[idx]}
<div
	use:portal={"body"}
	bind:this={floating.elements.floating}
	{...intersections.getFloatingProps()}
	style="{floating.floatingStyles};z-index:100000;" <!-- CHECK THE Z-INDEX -->
	transition:blur={{ duration: 300 }}
	class="bg-warning text-secondary md:rounded-[0.5vw] md:px-[0.75vw] md:py-[0.25vw] md:text-[1.1vw]"
>
	{anime.title}
</div>
{/if}
```

made the tooltip appear but it's in wrong position.
![image](https://github.com/skeletonlabs/floating-ui-svelte/assets/61817579/1971d643-6f20-4eee-868c-2d57e91720ce)

**Comment by baseplate-admin** [comment]
Hey uh, is there something i can do to move this forward?

**Comment by endigo9740** [comment]
@Hugos68 have you seen this? Any ideas?

@baseplate-admin Keep in mind Floating UI Svelte is pre-release software and not yet ready for production, so there's no guarantee it'll work in an issue-free manner quite yet. So make sure you're setting your expectations accordingly please. Thanks.

**Comment by baseplate-admin** [comment]
> Keep in mind Floating UI Svelte is pre-release software and not yet ready for production, so there's no guarantee it'll work in an issue-free manner quite yet.

That's why i opened this issue.

> Make sure you're setting your expectations accordingly please. Thanks.

That's why i am trying my best to move this forward :)

**Comment by Hugos68** [comment]
Hey @baseplate-admin, sorry for responding so late, I must have accidentally marked this as read when going through my notifications. Anways, although I definitely appreiciate you filing a bug report, without a minimal reproduction we can't do much. 
The reproduction you provided is your entire project, we don't have the resources to clone and skim through and entire project to bughunt, we expect *some* initial efforts from you.
Please provide a reproduction in: https://svelte-5-preview.vercel.app/
This ensures 2 things:
1. That the Svelte version is current
2. A consistent environment (node, npm, etc all become irrelevant)

**Comment by baseplate-admin** [comment]
Hey @Hugos68, i tried to reproduce it in [svelte repl](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACo1Wa2_bNhT9K5w6oNJgSa6zbqlrGy22Dt2GoUWzfbIMgxavbCYSKZCUHUPQf9-lnnbipAHimLy6j3NfRy6dhKegnemydATNwJk6H_PcGTnmmNuL3kNqAO9aFiq2kpmOFc8NSanYziPH6MhZRCIyPMulMqQkCWVAKpIomZHXjX1oFBWaGy7F6_enyvYcGVoY-V_OqIFRI0hSnrdHmSQaTHspNPyRSmq42A6Sz3IParj-KQwoGttYepB-kynYS4srcj7oO0jBSJHSjQ6T1qtfcL-BHDlnQIn9oinp7RstvxG3yvYTY1hDNGewoWpNBc9AkzlZNkgiU3YH9M2m5M1ouBtuUpii77-K28LogvxNuQZBNFAtBZlEzolybLO2yiHP6BZ0mMn4Lqyl4e3tXXCATX5mAPlaFNnGGk06aTV6AtbkEqwvAshXDjG8GIgUsM6txfNwxt_Fc3UJD5bntiBCBtcvBnRnTdZCrq-D23z7FKB338Xz8yU8v0OGbbpJ6REU-Uz1jitK_lWUC5ws8lHFL4bJrKe1rj2tTevh2Rq-GWrYHFaROB_FjOa5xTEnP2qDq-Y2eueTGqCW63pkviBun7LMQUxxrVMNffBYphLDFoJBwgWwRl55nj14uA2zsOEJyw2ifAU03j3cCop_9jQinN3XsMsPDeZuHRHsycp3iA47pKxPKWQgjP5HFrjw2JJHJLIFQyx0TKdPRYEplHhYkyXGXwVW932bR0c-4gsKf9sh1WGH3X1TmCetEe7ea03zlMY1QtviFBLTd87iyjhjKRyoggvolkOHG_Zz3ZIoiI0mVY3gZBh7o_p5oCABBcIuHGdmR34i4-Dq_aBeeSfjY1nW9br7qsu9pknPfp10RCF_Nt2wTOp2DQrwqYF7M0KGtCo2WSNlajhOKmm89D52drYbJzVnP_Jyrs4tkWtomLwxO-V2d2kDjhqvqw7vjDZZbLhgU7Pjel72UaAdmaFK7a6UQRCcRQuwR986pa9K5tr1Wt0dGuNrL6wnN8xoGpb1MeCsCiHnWjLoRP1-VpFjrReNixnPtl3VtYrnrXa9-lW_YCnVGgMd_KRIU6IFzX3cW3wXZWy685dv94eVPSppd5D5y3Hwi5U1kSIT1sFmIV20jXzFk6fnvg07Y3zfAcByT5u327yMnI1kx8jp0T1b3k7Sa1-sb7fV5-XFiphjCvMujdq8D9EdbqyOrobB7rWHHxrTTVqoeVkSVihaC8jk7ZhUjyr8w2brL_dUub7PZMYFFcav6c1bEXyES1rztx1QHxOQglF1JAxh-3pHmTzY2k-w9utxMPy_5NCXOY25OXoPO3fVdTO_t9df--ux811fawgouD7p82JgZIGlKYAcqIl3FvFM51SQLs0T-3e1_aKdu_r9VSFfo_aCfMrJw-kdOhEYeWOUpWLvRJhTdmMn052McP3HkdM1cxbiPNUAy5AnKCxD-x6o8OdkJhlPODBnalQB1ar6H_04U-eJCgAA) but i was unable to do so.

Because in order to create this issue i think the app has to go though svelte-kit build process.

So here's a minimal reproduction [repository](https://github.com/baseplate-admin/floating-ui-issue-128) that uses `svelte` + `tailwind` + `@floating-ui/svelte` + `svelte-portal`

**Comment by Hugos68** [comment]
> So here's a minimal reproduction [repository](https://github.com/baseplate-admin/floating-ui-issue-128) that uses svelte + tailwind + @floating-ui/svelte + svelte-portal.
What are the steps to reproduce the issue?

**Comment by Hugos68** [comment]
I've just deployed your repo: https://floating-ui-issue-128.vercel.app/
It seems to work, unless I'm, missing something?

**Comment by Hugos68** [comment]
@baseplate-admin I managed to fix it when moving to a component: https://floating-ui-issue-128.vercel.app/

**Comment by baseplate-admin** [comment]
Thanks a lot for your investigation.

---

>  I managed to fix it when moving to a component: https://floating-ui-issue-128.vercel.app/
Repo: https://github.com/Hugos68/floating-ui-issue-128

yep, it seems that moving to a component solves the issue. but the underlying problem still exists :(.

> Also, why do you use portal on the floating element? Just curious.

This can be better explained by @moonlitgrace

**Comment by moonlitgrace** [comment]
> why do you use portal on the floating element? Just curious.

hi @Hugos68 
we've been using `floating-ui-svelte` inside a `ScrollArea` with `overflow-y-scroll`, so its hiding elements overflowing on the x-axis.
```html
<ScrollArea class="overflow-y-scroll">
    <!-- reference element -->
    <!-- floating element -->
</ScrollArea>
```
even adding z-index didnt work, so we needed to render it outside scroll element (portal it).
to body maybe? well please let me know if theres better way to do this.

**Comment by endigo9740** [comment]
My immediate thought would be to pull the popover itself out of the ScrollArea. If it's hidden on load, it shouldn't matter where it's located. The only issue might be scoping. if that puts it outside of the scope of the `useFloating` hook in some manner that might cause issues.

**Comment by baseplate-admin** [comment]
> The only issue might be scoping. if that puts it outside of the scope of the useFloating hook in some manner that might cause issues.

But in the minimal reproduction doesn't have any `scrollarea`. My thought is the when we are using `floating-ui` in `@const` tag, vite removes/optimizes some properties that are not tree-shaked, thus we can see it working fine in development mode and the js part is removed in production mode

**Comment by Hugos68** [comment]
>well please let me know if theres better way to do this.

@moonlitgrace You could try `strategy: 'fixed'` in the `useFloating` configuration:
```js
useFloating({
    strategy: 'fixed'
});
```

**Comment by Hugos68** [comment]
Marking this as closed as it appears to be an issue with Svelte 5 @const, since it works fine in a normal component.

**Comment by baseplate-admin** [comment]
> Marking this as closed as it appears to be an issue with Svelte 5 @const, since it works fine in a normal component.

Hi, should we report this in `svelte` repo?

**Comment by Hugos68** [comment]
Yes, that would be the aproppiate place, though I would recommend to try the latest version as around a 100 new version have been published since this issue was originally brought up.
